name: Process coffee reference price
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * 1-5" # 14:00pm UTC-5

jobs:
  process-pdf-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - run: npm install
      - run: npm run build
      - run: npm run processRefPrice
